name: flutter_pptx
description: A Flutter package to create powerpoint presentations based on the open office XML spec.
version: 0.0.1

environment:
  sdk: '>=2.19.5 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  archive: ^3.3.6
  collection: ^1.17.0
  file: ^6.1.4
  flutter:
    sdk: flutter
  http: ^0.13.5
  json_annotation: ^4.8.0
  mustache_template: ^2.0.0
  path: ^1.8.3
  recase: ^4.1.0
  screenshot: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.1
  json_serializable: ^6.6.1
  build_version: ^2.1.1

flutter:
