name: dart_pptx
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=3.0.0-171.0.dev <4.0.0'

# Add regular dependencies here.
dependencies:
  archive: ^3.3.6
  collection: ^1.17.0
  file: ^6.1.4
  http: ^0.13.5
  image_size_getter: ^2.1.2
  json_annotation: ^4.8.0
  mustache_template: ^2.0.0
  path: ^1.8.2
  recase: ^4.1.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  json_serializable: ^6.6.1
  build_version: ^2.1.1
