name: dart_pptx
description: A package for creating pptx files from markdown or slide templates.
version: 0.1.2+1
repository: https://github.com/rodydavis/flutter_pptx
homepage: https://github.com/rodydavis/flutter_pptx

environment:
  sdk: ">=2.17.0 <3.0.0"

executables:
  md2pptx: main

platforms:
  android:
  ios:
  linux:
  macos:
  windows:
  web:

funding:
  - https://www.buymeacoffee.com/rodydavis
  - https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=WSH3GVC49GNNJ

dependencies:
  archive: ^3.3.6
  collection: ^1.17.0
  file: ^6.1.4
  http: ^0.13.5
  image_size_getter: ^2.1.2
  json_annotation: ^4.8.0
  mustache_template: ^2.0.0
  path: ^1.8.2
  recase: ^4.1.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  json_serializable: ^6.6.1
  build_version: ^2.1.1
